language: node_js
node_js:
  - 11
cache: npm
script:
  - npm run lint
env:
  - secure: "CSdHxN1KAkGuWf3080OC9ecHtZKn0yZ92dASbfC6up5DB4c2l+b4Bi0NncvvYltDAWWs77/erqVCIxRJ1IescdkqcxsPr7FTXgWjpbp3eHxIRPALtNbuo3jW0GbWD1sYRcv3DutJH7f3fG5+rr8d2/RNDG7QVKQyKjDzhFUELhtUpWGsAF7XIe5txkhCe6Df3GM/JleKfIWJVx+m33jEOr+DAvj3wvuFMXdr5GY+sxVgo2bVBPlN9aQWy3z3A2ir/yXVmkZwODCMvh64QORxzOlWwKP062H8JlosN02SVbGG5UGy5Th+8y7u/5VuDis1Hs8poc6fHn1c7KVK4GbT7t4ljnfsdhlyQR7Tgrciiyc137G3vl3x5tYbWpfPWlZPQUe4izHMOmxs4FzDU6YrEiVbUGoZKmp/F9Y1P3NaHKYjB0yikaaSFPTYA3E0EEO3gcPQsUgAbUx8EIvSOAgkeWVFrb8n5Opt1Zu/yQgWrc5+Q+cBO1JgxGnHXKzd7/KlO7pLGa9T0dUSvhkJf/6HLukikY9gAnhuOyLxeUJQvwOCW9fy/EijrTB03yWqPp6MeSAMLtF52kyBI6X71h4peSGi5sKqkvsSeUMYrV14JtZErtNvauB54jgFK4+vW7oKvnOxo0q8SmEl8zx2KRTh+/6EVg7UcZ7X5gxa4QzZi1s="
deploy:
  provider: script
  script: ./release.sh
  on:
    branch: travis
