language: node_js
node_js:
  - 11
cache: npm
script:
  - npm run lint
secure: "kr7vx2ExDyqI2YBcZjIgpObhdDWxaWHYb1Htvg0jpEjod3HrlHKVNAtwvgAIUGJ5Agtseif+2TD7gRyHmpXXAQdSlOv5ZbkQ2ks/V5NmovPu/5ETXLdIGJV+H7/Ir+0ULmQpDGyveWhAtuHaGOdtHHBCN7z3GUAATV3W7aTrNAXjvnlWGAFDY8MK3/BrPvlTtm2TsioEHcUbMvmr7o152THHlqEh04KpX4gvClIcDM8TbeYVQMlwwKuLuwlApPAUSk8BxEKFpaz7pGOosXXuj8ugwxuMCocYUE58USbj7ywy3nsjfRLj8Bua3i3BWzKF/1CBiR6/+8ZvEL/0TjS1oQZAqYbdTovE6Q9Ah4amh0wN1NMfNREEm50Bszbtpsu5bVXvRtNuMFmMAxffEQ4MTL3kfxeBwV4IH7bkMAFW3tYws6jlz90Tzx9LiU987o6HB5SjmeXMyKlwD0Wp5SZRoZKwxBxWo+lQBLOe2ohIZfnIXrlMeg5m4KTXeQr9dLz6p4AvU3iH22rZ2vCi3V3zkqYiYnMOxNKJlRZ7hJ0V/eFRzp3tJpjS6thFljcTEZaDAFpe+UxyyFPztmU7Jz+6FsWU4vOv0LoWqFYKZ5dTcP7qYEK/wGqtozqL0H7tAD0XbUHOD3gNJl9b+BcJBr6xDMt6euBqo7q3hdK9cAsBL48="
deploy:
  provider: script
  script: ./release.sh
  on:
    branch: travis
